use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use crate::{PYTHON_VERSION, TaskError, TaskResult, io_error, require_windows};

const MANAGED_CONFIG_HEADER: &str = "# Generated by cargo xtask bootstrap for RuViE.";
const WINDOWS_TOOLCHAIN: &str = "1.95.0-x86_64-pc-windows-msvc";

struct PythonProbe {
    executable: PathBuf,
    home: PathBuf,
}

pub(crate) fn run(repository: &Path) -> TaskResult<()> {
    require_windows("bootstrap")?;
    ensure_msvc_toolchain(repository)?;
    let python = find_or_install_python()?;
    let probe = probe_python(&python)?;
    write_cargo_config(repository, &probe)?;
    println!(
        "[bootstrap] CPython {PYTHON_VERSION}: {}",
        probe.home.display()
    );
    println!(
        "[bootstrap] wrote {}",
        repository.join(".cargo/config.toml").display()
    );
    println!("[bootstrap] run: cargo xtask publish");
    Ok(())
}

fn ensure_msvc_toolchain(repository: &Path) -> TaskResult<()> {
    run_checked(
        OsStr::new("rustup"),
        &[
            OsStr::new("toolchain"),
            OsStr::new("install"),
            OsStr::new(WINDOWS_TOOLCHAIN),
            OsStr::new("--profile"),
            OsStr::new("minimal"),
            OsStr::new("--component"),
            OsStr::new("clippy"),
            OsStr::new("--component"),
            OsStr::new("rustfmt"),
            OsStr::new("--no-self-update"),
        ],
    )?;
    let status = Command::new("rustup")
        .args(["override", "set", WINDOWS_TOOLCHAIN])
        .current_dir(repository)
        .status()
        .map_err(|error| TaskError::new(format!("cannot execute rustup override: {error}")))?;
    if !status.success() {
        return Err(TaskError::new(format!(
            "rustup could not select {WINDOWS_TOOLCHAIN}: {status}"
        )));
    }
    Ok(())
}

fn find_or_install_python() -> TaskResult<PathBuf> {
    let find_arguments = [
        OsStr::new("python"),
        OsStr::new("find"),
        OsStr::new("--managed-python"),
        OsStr::new("--no-project"),
        OsStr::new(PYTHON_VERSION),
    ];
    let first = command_output(OsStr::new("uv"), &find_arguments)?;
    let output = if first.status.success() {
        first
    } else {
        let install_arguments = [
            OsStr::new("python"),
            OsStr::new("install"),
            OsStr::new(PYTHON_VERSION),
        ];
        run_checked(OsStr::new("uv"), &install_arguments)?;
        command_output(OsStr::new("uv"), &find_arguments)?
    };
    if !output.status.success() {
        return Err(command_failure("uv python find", &output));
    }
    let text = String::from_utf8(output.stdout)
        .map_err(|error| TaskError::new(format!("uv returned a non-UTF-8 path: {error}")))?;
    let path = PathBuf::from(text.trim());
    if path.as_os_str().is_empty() {
        return Err(TaskError::new("uv returned an empty Python path"));
    }
    canonical_file(&path, "managed Python executable")
}

fn probe_python(python: &Path) -> TaskResult<PythonProbe> {
    let script = "import platform,sys; print(platform.python_implementation()); print(platform.python_version()); print(sys.base_prefix); print(sys._is_gil_enabled()); print(platform.machine())";
    let output = command_output(python.as_os_str(), &[OsStr::new("-c"), OsStr::new(script)])?;
    if !output.status.success() {
        return Err(command_failure("managed Python probe", &output));
    }
    let text = String::from_utf8(output.stdout).map_err(|error| {
        TaskError::new(format!("managed Python returned non-UTF-8 output: {error}"))
    })?;
    let lines: Vec<&str> = text.lines().collect();
    if lines.len() != 5 {
        return Err(TaskError::new(format!(
            "managed Python probe returned {} lines instead of 5",
            lines.len()
        )));
    }
    let implementation = lines.first().copied().unwrap_or("unknown implementation");
    let version = lines.get(1).copied().unwrap_or("unknown version");
    if implementation != "CPython" || version != PYTHON_VERSION {
        return Err(TaskError::new(format!(
            "RuViE requires CPython {PYTHON_VERSION}; found {implementation} {version}"
        )));
    }
    if lines.get(3).copied() != Some("True") {
        return Err(TaskError::new(
            "RuViE requires the standard-GIL CPython build",
        ));
    }
    let architecture = lines.get(4).copied().unwrap_or_default();
    if !architecture.eq_ignore_ascii_case("AMD64") && !architecture.eq_ignore_ascii_case("x86_64") {
        return Err(TaskError::new(format!(
            "RuViE Windows packages require x86_64 CPython; found {architecture}"
        )));
    }
    let home = lines
        .get(2)
        .map(PathBuf::from)
        .ok_or_else(|| TaskError::new("managed Python did not report sys.base_prefix"))?;
    Ok(PythonProbe {
        executable: canonical_file(python, "managed Python executable")?,
        home: canonical_directory(&home, "managed Python home")?,
    })
}

fn write_cargo_config(repository: &Path, python: &PythonProbe) -> TaskResult<()> {
    let cargo_directory = repository.join(".cargo");
    fs::create_dir_all(&cargo_directory)
        .map_err(|error| io_error("create .cargo directory", &cargo_directory, error))?;
    let config = cargo_directory.join("config.toml");
    if config.exists() {
        let existing = fs::read_to_string(&config)
            .map_err(|error| io_error("read existing Cargo config", &config, error))?;
        if !existing.starts_with(MANAGED_CONFIG_HEADER) {
            return Err(TaskError::new(format!(
                "refusing to replace non-RuViE-managed Cargo config {}",
                config.display()
            )));
        }
    }
    let executable = toml_path(&python.executable)?;
    let home = toml_path(&python.home)?;
    let contents = format!(
        "{MANAGED_CONFIG_HEADER}\n# Machine-local paths pin PyO3 and the bundled runtime to one interpreter.\n[alias]\nxtask = \"run --locked --package xtask --\"\n\n[env]\nPYO3_PYTHON = {{ value = \"{executable}\", force = true }}\nRUVIE_PYTHON_HOME = {{ value = \"{home}\", force = true }}\nPYO3_ENVIRONMENT_SIGNATURE = {{ value = \"ruvie-cpython-{PYTHON_VERSION}-standard-gil\", force = true }}\n"
    );
    replace_owned_file(&config, contents.as_bytes())
}

fn toml_path(path: &Path) -> TaskResult<String> {
    let text = path
        .to_str()
        .ok_or_else(|| TaskError::new(format!("path is not valid Unicode: {}", path.display())))?;
    let text = text
        .strip_prefix(r"\\?\")
        .or_else(|| text.strip_prefix("//?/"))
        .unwrap_or(text);
    let mut escaped = String::with_capacity(text.len());
    for character in text.chars() {
        match character {
            '\\' => escaped.push('/'),
            '"' => escaped.push_str("\\\""),
            '\n' | '\r' => {
                return Err(TaskError::new("Cargo config paths cannot contain newlines"));
            }
            other => escaped.push(other),
        }
    }
    Ok(escaped)
}

fn replace_owned_file(path: &Path, contents: &[u8]) -> TaskResult<()> {
    let parent = path
        .parent()
        .ok_or_else(|| TaskError::new("managed file has no parent"))?;
    let temporary = parent.join(format!("config.toml.tmp-{}", std::process::id()));
    let backup = parent.join(format!("config.toml.backup-{}", std::process::id()));
    if temporary.exists() || backup.exists() {
        return Err(TaskError::new(
            "stale managed Cargo config staging file exists",
        ));
    }
    fs::write(&temporary, contents)
        .map_err(|error| io_error("write staged Cargo config", &temporary, error))?;
    if path.exists() {
        fs::rename(path, &backup).map_err(|error| io_error("backup Cargo config", path, error))?;
        if let Err(error) = fs::rename(&temporary, path) {
            let restore = fs::rename(&backup, path);
            return match restore {
                Ok(()) => Err(io_error("activate Cargo config", &temporary, error)),
                Err(restore_error) => Err(TaskError::new(format!(
                    "cannot activate Cargo config ({error}) or restore backup ({restore_error})"
                ))),
            };
        }
        fs::remove_file(&backup)
            .map_err(|error| io_error("remove Cargo config backup", &backup, error))?;
    } else {
        fs::rename(&temporary, path)
            .map_err(|error| io_error("activate Cargo config", &temporary, error))?;
    }
    Ok(())
}

fn canonical_file(path: &Path, description: &str) -> TaskResult<PathBuf> {
    if !path.is_file() {
        return Err(TaskError::new(format!(
            "{description} is missing: {}",
            path.display()
        )));
    }
    path.canonicalize()
        .map_err(|error| io_error("canonicalize file", path, error))
}

fn canonical_directory(path: &Path, description: &str) -> TaskResult<PathBuf> {
    if !path.is_dir() {
        return Err(TaskError::new(format!(
            "{description} is missing: {}",
            path.display()
        )));
    }
    path.canonicalize()
        .map_err(|error| io_error("canonicalize directory", path, error))
}

fn command_output(program: &OsStr, arguments: &[&OsStr]) -> TaskResult<Output> {
    Command::new(program)
        .args(arguments)
        .output()
        .map_err(|error| {
            TaskError::new(format!(
                "cannot execute {}: {error}",
                program.to_string_lossy()
            ))
        })
}

fn run_checked(program: &OsStr, arguments: &[&OsStr]) -> TaskResult<()> {
    let status = Command::new(program)
        .args(arguments)
        .status()
        .map_err(|error| {
            TaskError::new(format!(
                "cannot execute {}: {error}",
                program.to_string_lossy()
            ))
        })?;
    if status.success() {
        Ok(())
    } else {
        Err(TaskError::new(format!(
            "{} failed with {status}",
            program.to_string_lossy()
        )))
    }
}

fn command_failure(operation: &str, output: &Output) -> TaskError {
    TaskError::new(format!(
        "{operation} failed with {}: {}",
        output.status,
        String::from_utf8_lossy(&output.stderr).trim()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_path_removes_windows_extended_prefix() -> TaskResult<()> {
        assert_eq!(
            toml_path(Path::new(r"\\?\C:\Users\editor\python.exe"))?,
            "C:/Users/editor/python.exe"
        );
        assert_eq!(
            toml_path(Path::new("//?/C:/Users/editor/python.exe"))?,
            "C:/Users/editor/python.exe"
        );
        Ok(())
    }
}
