[package]
name = "app"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lints]
workspace = true

[features]
default = []
opencolorio = ["library/opencolorio"]

[dependencies]
eframe = { version = "0.33.3", features = ["serde"] }
egui = "0.33.3"
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
egui_dock = "0.18.0"
rfd = "0.16"
env_logger = "0.11"
library = { version = "0.1.0", path = "../library" }
uuid = { version = "1.19.0", features = ["serde", "v4"] }
ordered-float = { version = "5.1.0", features = ["serde"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }

[dev-dependencies]
tempfile = "3.27"

[package.metadata.bundle]
name = "My Video Editor App"
identifier = "me.liesegang.videoeditorapp"
icon = ["assets/icon_32x32.png", "assets/icon_128x128.png"]
version = "0.1.0"
copyright = "Copyright (c) 2025 Liesegang"
category = "Productivity"
short_description = "A video production software."
