name: Build and Package Rust cx-qt App

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4

      - name: Setup Qt
        uses: jurplel/install-qt-action@c6c7281365daef91a238e1c2ddce4eaa94a2991d
        with:
          version: 6.8.2
          host: ${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'mac' || 'linux' }}
          target: 'desktop'

      - name: Build Release
        run: cargo build -p app --release

      - name: Package for Linux
        if: runner.os == 'Linux'
        run: |
          cargo install cargo-deb --version 1.45.0 || true
          cargo deb --no-strip
          mkdir -p installer
          cp target/debian/*.deb installer/

      - name: Package for macOS
        if: runner.os == 'macos'
        run: |
          cargo install cargo-bundle || true
          cargo bundle --release
          mkdir -p installer
          cp target/release/bundle/*.dmg installer/

      - name: Package for Windows
        if: runner.os == 'Windows'
        run: |
          mkdir installer
          powershell Compress-Archive -Path target\release\*.exe -DestinationPath installer\app.zip

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer-${{ runner.os }}
          path: installer/
