name: Build and Package Rust cx-qt App for Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4

      - name: Setup Qt
        uses: jurplel/install-qt-action@c6c7281365daef91a238e1c2ddce4eaa94a2991d
        with:
          version: 6.8.2
          host: linux
          target: 'desktop'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libavutil-dev \
            libvulkan-dev \
            libxcb-render0-dev \
            libxcb-render-util0-dev \
            libxcb-xkb-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev

      - name: Build Release
        run: cargo build -p app --release

      - name: Package
        run: |
          cargo install cargo-deb --version 1.45.0 || true
          cargo deb --no-strip
          mkdir -p installer
          cp target/debian/*.deb installer/

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer-linux
          path: installer/
